#!/usr/local/bin/ruby
require 'rubygems'
require 'daemons'
require 'yaml'
require 'erb'

class Hash
  def with_symbols!
    self.keys.each{|key| self[key.to_s.to_sym] = self[key] }; self
  end
end

options = YAML.load( ERB.new( IO.read( "config/daemons.yml" )).result).with_symbols!
options[:dir_mode] = options[:dir_mode].to_sym

Daemons.run 'poll_twitter.rb', options

